apiVersion: v1
kind: Service
metadata:
    name: "azhskubernetescluster01-47ec"
    labels:
        app: "azhskubernetescluster01-47ec"
spec:
    type: LoadBalancer
    ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: http
    selector:
        app: "azhskubernetescluster01-47ec"